---
# - hosts: 127.0.0.1
#   # user: root
#   connection: local
#   become: yes
#   roles:
#     - role: elastic.elasticsearch
#   vars:
#     es_major_version: "5.x"
#     es_version: "5.0.0"
#     es_enable_xpack: false
#     es_instance_name: "master1"
#     es_heap_size: "1g"
#     es_config:
#       cluster.name: "test-cluster"
#       discovery.zen.ping.unicast.hosts: "192.168.158.216:9300"
#       http.port: 9200
#       transport.tcp.port: 9300
#       node.data: false
#       node.master: true
#       bootstrap.memory_lock: false
#     es_scripts: false
#     es_templates: false
#     es_version_lock: false
#     ansible_user: ansible
#     es_plugins:
#      - plugin: ingest-geoip

- hosts: datanode1
  remote_user: root
  # ansible_user: root
  roles:
    - role: elastic.elasticsearch
  vars:
    es_major_version: "5.x"
    es_version: "5.0.0"
    es_enable_xpack: false
    es_instance_name: "datanode1"
    es_heap_size: "1g"
    es_data_dirs: 
      - "/opt/elasticsearch"
    es_config:
      cluster.name: "test-cluster"
      discovery.zen.ping.unicast.hosts: "192.168.158.217:9300"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: ansible
    es_api_port: 9200
    es_plugins:
      - plugin: ingest-geoip
    
- hosts: datanode2
  # remote_user: root
  # ansible_user: root
  roles:
    - role: elastic.elasticsearch
  vars:
    es_major_version: "5.x"
    es_version: "5.0.0"
    es_enable_xpack: false
    es_instance_name: "datanode2"
    es_heap_size: "1g"
    es_api_port: 9201
    es_config:
      discovery.zen.ping.unicast.hosts: "192.168.158.218:9300"
      http.port: 9201
      transport.tcp.port: 9301
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
      cluster.name: "test-cluster"
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_api_port: 9201
    ansible_user: ansible
    es_plugins:
      - plugin: ingest-geoip
