---
- name: copy kubelet-service file
  template: src="kubelet.service.j2" dest=/etc/systemd/system/kubelet.service owner=root group=root mode=0644
  register: kubelet_service

- name: create kubernetes manifest config directory
  file: path={{ manifest_config_dir }} state=directory
  register: manifest

- name: create kubernetes config directory
  file: path={{ kube_config_dir }} state=directory
  register: config_dir

- name: copy kubeadmin config file
  template: src="kubeadminconfig.j2" dest={{ kube_config_dir }}/kubeadminconfig
  register: config

- name: copy kubelet config file
  template: src="kubelet.j2" dest={{ kube_config_dir }}/kubelet
  register: kubeletconfig

- name: copy kubelet.yaml
  template: src=kubelet.yaml.j2 dest={{ kube_config_dir }}/kubelet.yaml

- name: copy kubelet.conf
  template: src=kubelet.conf.j2 dest={{ kube_config_dir }}/kubelet.conf

- name: copy kubectl binary and kubelet binary download script
  copy: src=getkube.sh dest=/opt/getkube.sh

- name: download k8s binary
  shell: "sh /opt/getkube.sh {{ k8s_version }} NODE"
  
- name: create kubelet directory
  file: path=/var/lib/kubelet state=directory
  
- name: start and enable kubelet on node
  service: name=kubelet enabled=yes state=started daemon_reload=yes
  register: kubelet_start_node
