---
- name: install wget if not 
  yum:
    name: wget 
    state: present

- name: install cloudera repo 
  command: "{{ item }}"
  with_items:
    - wget https://archive.cloudera.com/cm6/6.1.0/redhat7/yum/cloudera-manager.repo -P /etc/yum.repos.d/
    - sudo rpm --import https://archive.cloudera.com/cm6/6.1.0/redhat7/yum/RPM-GPG-KEY-cloudera

- name: install oracle jdk 
  yum:
    name: oracle-j2sdk1.8
    state: present

- name: install cloudera manager package
  yum: 
    name: "{{ item }}"
  with_items:
    - cloudera-manager-daemons
    - cloudera-manager-agent
    - cloudera-manager-server

- name: enable TLS-automations
  command: sudo JAVA_HOME=/usr/java/jdk1.8.0_141-cloudera /opt/cloudera/cm-agent/bin/certmanager setup --configure-services




