- include_vars: ../../../../whis-platform/inventory/group_vars/local/vault
- name: Add Artifactory repo
  yum_repository:
    name: Artifactory
    description: Artifactory taas private repo
    baseurl: https://{{docker_registry_username| trim| urlencode()}}:{{docker_registry_password| trim}}@na.artifactory.swg-devops.com/artifactory/wh-imaging-prereqs-rpm-local/
    gpgcheck: no
  when: setup=="private"

- name: Add docker-ce-stable repo
  yum_repository:
    name: docker-ce
    description: docker-ce stable repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
  when: setup=="public"

- name: Add kubernetes repo
  yum_repository:
    name: kubernetes
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes
  when: setup=="public"