---
- name: Install Docker dependency
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - yum-utils
    - lvm2
    - device-mapper-persistent-data

- name: install docker repo
  command: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

- name: Install Docker
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - docker-ce

- name: Start Docker Daemon
  service: name=docker enabled=no state=started daemon_reload=yes

- name: "Load br_netfilter kernel module"
  modprobe:
    name: br_netfilter
    state: present

- name: "Set bridge-nf-call-iptables"
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1

- name: "Set ip_forward"
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: "Create a directory for cni plugin"
  file: path={{ cni_bin_dir }} state=directory

- name: "Get cni binary"
  unarchive:
    src: "https://github.com/containernetworking/plugins/releases/download/{{ cni_version }}/cni-plugins-amd64-{{ cni_version }}.tgz"
    dest: "{{ cni_bin_dir }}"
    remote_src: yes

- name: disable selinux
  selinux:
    state: disabled

- name: disable selinux in file
  lineinfile: "dest=/etc/selinux/config state=present regexp='^SELINUX=' line='SELINUX=disabled'"
