---
- name: install vim
  yum:
    name: vim
    state: present

- name: Copy javajdk rpm with owner and permissions
  copy:
    src: /root/jdk-8u202-linux-x64.rpm
    dest: /root/jdk-8u202-linux-x64.rpm
    owner: root
    group: root
    mode: '0777'

- name: add hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  with_items:
    - 172.18.10.200 vega-bi-r01m01.platfio.com vega-bi-r01m01
    - 172.18.10.201 vega-bi-r01n01.platfio.com vega-bi-r01n01
    - 172.18.10.202 vega-bi-r01n02.platfio.com vega-bi-r01n02
    - 172.18.10.203 vega-bi-r01d01.platfio.com vega-bi-r01d01
    - 172.18.10.204 vega-bi-r02d02.platfio.com vega-bi-r02d02

- name: Disable IPv6 with sysctl
  sysctl: name={{ item }} value=1 state=present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: install java jdk8
  yum:
    name: /root/jdk-8u202-linux-x64.rpm
    state: present

- name: Insert a line at the end of a file.
  lineinfile:
    path: /etc/bashrc
    line: "{{ item }}"
  with_items:
    - export PATH=$PATH:/usr/java/jdk1.8.0_202-amd64/bin/
    - export JAVA_HOME=/usr/java/jdk1.8.0_202-amd64

- name: source bashrc
  shell: source /etc/bashrc && echo $JAVA_HOME

# Disable SELinux
- name: disable selinux  
  selinux:
    state: disabled

- name: install ntp
  yum:
    name: ntp
    state: present

- name: Enable service ntpd, and not touch the state
  service:
    name: ntpd
    enabled: yes

- name: replace ntp config
  template: src=ntp.conf dest=/etc/ntp.conf

- name: Start service ntpd, if not started
  service:
    name: ntpd
    state: started

- name: update time ntp
  shell: ntpdate -u time.google.com

- name: Synchronize the hardware clock to the system clock
  shell: hwclock --systohc

- name: check date
  shell: date