---
#JAVA_HOME=/usr/java/jdk1.8.0_141-cloudera
- name: Set JAVA_HOME
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: ''
    line: "{{ item }}"
  with_items:
    - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
    - export PATH=$PATH:$JAVA_HOME/bin

# - name: source /etc/environment
  # shell: "source /etc/environment"
