- name: upgrade kubeadm
  yum:
    name: kubeadm
    state: "{{kubeadm_version}}"
    
- name: pip install pexpect
  pip:
    name: pexpect
    extra_args: -i https://{{docker_registry_username| trim}}:{{docker_registry_password| trim}}@na.artifactory.swg-devops.com/artifactory/api/pypi/wh-imaging-pypi-local/simple

- name: Run kubeadm upgrade
  expect:
    command: kubeadm upgrade apply {{upgrade_version}}
    echo: yes
    timeout: 250
    responses:
      upgrade?: "y"