---
# This playbook deploys a kubernetes cluster with the default addons.

# Install yum-repo
- hosts: all
  roles:
    - yum-repo
  tags:
    - yum-repo

# Install sslcert
- hosts: sslhost
  roles:
    - sslcert 
  tags:
    - sslcert

# Install etcd
- hosts: etcd
  roles:
    - etcd
  tags:
    - etcd

# Install container runtime
- hosts: all
  roles:
    - { role: docker, when: use_containerd == 'false' }
    - { role: containerd, when: use_containerd == 'true' }

# install haproxy
- hosts: masters
  roles:
    - haproxy
  tags:
    - haproxy

# install keepalived
- hosts: masters
  roles:
    - keepalived
  tags:
    - keepalived

# install kubernetes master services
- hosts: masters
  roles:
    - master
  tags:
    - master

# install kubernetes on the nodes
- hosts: node
  roles:
    - node
  tags:
    - node
